### ISSUE TITLE
[1.15.2] [Enhancement] Config folder file

### ISSUE THREAD

**Issue by Yamza** [MC-U-Team/Overworld-Mirror#4] opened 2020-02-20 18:54 UTC
I would like to be able to include a configuration for the dimension settings in the config folder to include custom settings for modpacks.

**Comment by HyCraftHD** [comment] 2020-02-20 18:59
There is a configuration file. It is in the world! (overworldmirror-server.toml)
For modpacks there is a defaultconfig folder in the run directory that will copy the config when a new world is created (works also on the server)

**Comment by Yoosk** [comment] 2020-02-20 20:10
I would too prefer normal config in `config` directory instead. Having multiple directories for config is not a best way for a modpack developer.

**Comment by HyCraftHD** [comment] 2020-02-20 20:12
It does not make sense to have world specific configuration in a common location.
Every world can have different settings. Please adapt to the new forge config system!
I'll close it as I won't change that.

**Closed as completed by HyCraftHD** 2020-02-20 20:12 UTC

**Comment by Yamza** [comment] 2020-02-20 20:33
I could see your point if your config was way more user intuitive, but what is the realistic possibility of any normal users configuring those settings, and then wanting to do so differently for each separate save. Also, if this is your planned outlook for pack configuration you might want to indicate how that is meant to work since this is the first mod I've seen that wants to work in this manner.

> This mod can be packed in every modpack you want :)

Not exactly telling people how to do it.

**Comment by HyCraftHD** [comment] 2020-02-20 20:38
Thats a valid point!
Will update the documentation soon. The lack of docs is because this mod was designed for a private modpack but I eventually decided that it might be useful for other people.

**Comment by Yamza** [comment] 2020-02-20 20:41
Sounds good, thanks.
